server {
    listen       8080;
    server_name  localhost;

    access_log  /dev/stdout;
    error_log   /dev/stderr warn;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }
}
